import 'package:srik_cli/models/project_config.dart';
import 'package:srik_cli/utils/string_utils.dart';

String srikYamlTemplate(ProjectConfig c) => '''
# srik_cli configuration. Used by `srik add` commands.
version: 0.1.0
project_name: ${c.projectName}
architecture: clean
state_management: riverpod
routing: go_router
storage: shared_preferences
network: dio
design_system:
  preset: material
  brand_color: "${c.brandColor}"
features:
  - home
''';

String analysisOptionsTemplate(ProjectConfig c) => '''
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    avoid_print: true
    require_trailing_commas: true

analyzer:
  errors:
    invalid_annotation_target: ignore
''';

String readmeTemplate(ProjectConfig c) {
  final title = StringUtils.toTitleCase(c.projectName);
  return '''
# $title

${c.description}

Generated by [srik_cli](https://pub.dev/packages/srik_cli) with **Clean Architecture + Riverpod**.

## Stack

- **Architecture:** Clean Architecture (domain → data → presentation)
- **State management:** [Riverpod](https://riverpod.dev/)
- **Routing:** [go_router](https://pub.dev/packages/go_router)
- **Networking:** [Dio](https://pub.dev/packages/dio)
- **Local storage:** [shared_preferences](https://pub.dev/packages/shared_preferences)
- **Functional error handling:** [dartz](https://pub.dev/packages/dartz)

## Structure

\`\`\`
lib/
├── core/                # shared infrastructure
│   ├── constants/       # design tokens (colors, spacing, theme)
│   ├── error/           # exceptions & failures
│   ├── network/         # Dio client
│   ├── router/          # go_router config
│   └── storage/         # local storage wrapper
├── features/            # feature modules
│   └── home/
│       ├── data/        # repositories impl, models, data sources
│       ├── domain/      # entities, repository interfaces
│       └── presentation/# screens, widgets, providers
├── app.dart
└── main.dart
\`\`\`

## Run

\`\`\`bash
flutter pub get
flutter run
\`\`\`

## Add features

\`\`\`bash
srik add feature <feature_name>
\`\`\`

## License

Add your license here.
''';
}

String gitignoreTemplate(ProjectConfig c) => '''
# Miscellaneous
*.class
*.log
*.pyc
*.swp
.DS_Store
.atom/
.build/
.buildlog/
.history
.svn/
.swiftpm/
migrate_working_dir/

# IntelliJ / Android Studio
*.iml
*.ipr
*.iws
.idea/

# VS Code
.vscode/

# Flutter / Dart / Pub
**/doc/api/
**/ios/Flutter/.last_build_id
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.pub-cache/
.pub/
/build/

# Symbolication
app.*.symbols
app.*.map.json

# Obfuscation
app.*.symbols

# Android Studio
android/.gradle
android/captures/
android/gradlew
android/gradlew.bat
android/local.properties
android/**/GeneratedPluginRegistrant.java
android/key.properties
*.jks

# iOS / macOS
**/ios/**/*.mode1v3
**/ios/**/*.mode2v3
**/ios/**/*.moved-aside
**/ios/**/*.pbxuser
**/ios/**/*.perspectivev3
**/ios/**/*sync/
**/ios/**/.sconsign.dblite
**/ios/**/.tags*
**/ios/**/.vagrant/
**/ios/**/DerivedData/
**/ios/**/Icon?
**/ios/**/Pods/
**/ios/**/.symbols/
**/ios/**/profile
**/ios/**/xcuserdata
**/ios/.generated/
**/ios/Flutter/.last_build_id
**/ios/Flutter/App.framework
**/ios/Flutter/Flutter.framework
**/ios/Flutter/Flutter.podspec
**/ios/Flutter/Generated.xcconfig
**/ios/Flutter/ephemeral
**/ios/Flutter/app.flx
**/ios/Flutter/app.zip
**/ios/Flutter/flutter_assets/
**/ios/Flutter/flutter_export_environment.sh
**/ios/ServiceDefinitions.json
**/ios/Runner/GeneratedPluginRegistrant.*

# Exceptions
!**/ios/**/default.mode1v3
!**/ios/**/default.mode2v3
!**/ios/**/default.pbxuser
!**/ios/**/default.perspectivev3
''';
