import 'package:srik_cli/models/project_config.dart';
import 'package:srik_cli/utils/string_utils.dart';

String homeEntityTemplate(ProjectConfig c) => '''
import 'package:equatable/equatable.dart';

/// Pure domain entity. No Flutter / framework dependencies.
class HomeEntity extends Equatable {
  final String title;
  final String subtitle;

  const HomeEntity({
    required this.title,
    required this.subtitle,
  });

  @override
  List<Object?> get props => [title, subtitle];
}
''';

String homeRepositoryTemplate(ProjectConfig c) => '''
import 'package:dartz/dartz.dart';

import '../../../../core/error/failures.dart';
import '../entities/home_entity.dart';

/// Abstract repository contract. Implemented in the data layer.
abstract class HomeRepository {
  Future<Either<Failure, HomeEntity>> getWelcomeMessage();
}
''';

String homeRepositoryImplTemplate(ProjectConfig c) => '''
import 'package:dartz/dartz.dart';

import '../../../../core/error/failures.dart';
import '../../domain/entities/home_entity.dart';
import '../../domain/repositories/home_repository.dart';

/// Concrete repository. Wire up to remote/local data sources as needed.
class HomeRepositoryImpl implements HomeRepository {
  @override
  Future<Either<Failure, HomeEntity>> getWelcomeMessage() async {
    try {
      // TODO: replace with real data source calls.
      await Future.delayed(const Duration(milliseconds: 300));
      return const Right(
        HomeEntity(
          title: 'Welcome',
          subtitle: 'Your app is ready. Start building!',
        ),
      );
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }
}
''';

String homeProviderTemplate(ProjectConfig c) => '''
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../data/repositories/home_repository_impl.dart';
import '../../domain/entities/home_entity.dart';
import '../../domain/repositories/home_repository.dart';

/// Repository provider.
final homeRepositoryProvider = Provider<HomeRepository>((ref) {
  return HomeRepositoryImpl();
});

/// Home screen state, fetched on first watch.
final homeWelcomeProvider = FutureProvider<HomeEntity>((ref) async {
  final repo = ref.watch(homeRepositoryProvider);
  final result = await repo.getWelcomeMessage();
  return result.fold(
    (failure) => throw Exception(failure.message),
    (entity) => entity,
  );
});
''';

String homeScreenTemplate(ProjectConfig c) {
  final title = StringUtils.toTitleCase(c.projectName);
  return '''
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_spacing.dart';
import '../../../../core/constants/app_text_styles.dart';
import '../providers/home_provider.dart';

class HomeScreen extends ConsumerWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final welcomeAsync = ref.watch(homeWelcomeProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('$title'),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(AppSpacing.lg),
          child: welcomeAsync.when(
            loading: () =>
                const Center(child: CircularProgressIndicator()),
            error: (e, _) => Center(
              child: Text(
                'Error: \$e',
                style: AppTextStyles.body
                    .copyWith(color: AppColors.error),
              ),
            ),
            data: (entity) => Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(entity.title, style: AppTextStyles.h1),
                const SizedBox(height: AppSpacing.sm),
                Text(entity.subtitle, style: AppTextStyles.body),
                const Spacer(),
                Center(
                  child: ElevatedButton(
                    onPressed: () {
                      ref.invalidate(homeWelcomeProvider);
                    },
                    child: const Text('Refresh'),
                  ),
                ),
                const SizedBox(height: AppSpacing.lg),
                Center(
                  child: Text(
                    'Generated by srik_cli',
                    style: AppTextStyles.caption,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
''';
}
