import 'package:srik_cli/models/project_config.dart';
import 'package:srik_cli/utils/string_utils.dart';

/// Templates shared across all architectures.
class CommonTemplates {
  static String pubspec(ProjectConfig c) => '''
name: ${c.projectName}
description: ${c.description}
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.0.0

  # Networking
  dio: ^5.4.0

  # Local storage
  shared_preferences: ^2.2.0

  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
''';

  static String analysisOptions(ProjectConfig c) => '''
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    require_trailing_commas: true

analyzer:
  errors:
    invalid_annotation_target: ignore
''';

  static String srikYaml(ProjectConfig c) {
    final flavorsBlock = c.hasFlavors
        ? 'flavors:\n${c.flavors.map((f) => '  - $f').join('\n')}\n'
        : '';
    return '''
# srik_cli configuration.
#
# This file is read by `srik add feature` and `srik add screen` to know
# how to generate new code. It is rewritten when features are appended.
# Avoid adding comments below — they will not be preserved on regeneration.
#
# Fields:
#   project_name      Dart package name (lowercase + underscores).
#   architecture      clean | mvvm | feature-first | simple.
#   state_management  Always "riverpod" in v0.3 (more options planned).
#   routing           Always "go_router" in v0.3.
#   storage           Always "shared_preferences" in v0.3.
#   network           Always "dio" in v0.3.
#   design_system.preset      material | vibrant | minimal.
#   design_system.gradient    true to include app_gradients.dart.
#   design_system.spacing     compact | normal | spacious.
#   design_system.brand_color #RRGGBB or #AARRGGBB.
#   flavors                   Build flavors, one per line (omitted if none).
#   features                  Tracked feature names, one per line.
version: 0.3.0
project_name: ${c.projectName}
architecture: ${c.architecture.id}
state_management: riverpod
routing: go_router
storage: shared_preferences
network: dio
design_system:
  preset: ${c.designPreset.id}
  gradient: ${c.useGradient}
  spacing: ${c.spacingScale.id}
  brand_color: "${c.brandColor}"
${flavorsBlock}features:
  - home
''';
  }

  static String readme(ProjectConfig c) {
    final title = StringUtils.toTitleCase(c.projectName);
    return '''
# $title

${c.description}

Generated by [srik_cli](https://pub.dev/packages/srik_cli).

## Configuration

- **Architecture:** ${c.architecture.label}
- **State management:** Riverpod
- **Routing:** go_router
- **Networking:** Dio
- **Local storage:** shared_preferences
- **Design preset:** ${c.designPreset.id}
- **Gradient theme:** ${c.useGradient ? 'enabled' : 'disabled'}
- **Spacing scale:** ${c.spacingScale.id}${c.hasFlavors ? '\n- **Flavors:** ${c.flavors.join(', ')}' : ''}

## Run

```bash
flutter pub get
flutter run${c.hasFlavors ? ' --flavor ${c.flavors.first} -t lib/main_${c.flavors.first}.dart' : ''}
```
${c.hasFlavors ? _readmeFlavorsSection(c) : ''}
## Add features

```bash
srik add feature <feature_name>
```

## License

Add your license here.
''';
  }

  static String _readmeFlavorsSection(ProjectConfig c) {
    final runLines = c.flavors
        .map((f) => 'flutter run --flavor $f -t lib/main_$f.dart')
        .join('\n');
    final buildLines = c.flavors
        .map((f) => 'flutter build apk --flavor $f -t lib/main_$f.dart')
        .join('\n');
    return '''

## Flavors

This project has the following build flavors: **${c.flavors.join(', ')}**.

Each flavor has its own entry point (`lib/main_<flavor>.dart`) and configuration
in `AppConfig` (app name, API base URL, bundle suffix).

### Run

```bash
$runLines
```

### Build

```bash
$buildLines
```

- **Android** is configured automatically (`productFlavors` in
  `android/app/build.gradle.kts`).
- **iOS** requires one-time manual setup in Xcode — see
  [FLAVORS_IOS_SETUP.md](FLAVORS_IOS_SETUP.md).
- **VS Code:** a launch configuration per flavor is in `.vscode/launch.json`.
''';
  }

  /// VS Code launch configurations — one per flavor.
  static String vscodeLaunchJson(ProjectConfig c) {
    final configs = c.flavors.map((f) => '''
    {
      "name": "$f",
      "request": "launch",
      "type": "dart",
      "program": "lib/main_$f.dart",
      "args": ["--flavor", "$f"]
    }''').join(',\n');
    return '''
{
  "version": "0.2.0",
  "configurations": [
$configs
  ]
}
''';
  }

  /// Step-by-step iOS flavor setup. We do NOT edit the .pbxproj
  /// programmatically — these are manual Xcode steps.
  static String flavorsIosSetup(ProjectConfig c) {
    final flavorList = c.flavors.map((f) => '`$f`').join(', ');
    final runExample = 'flutter run --flavor ${c.flavors.first} '
        '-t lib/main_${c.flavors.first}.dart';
    final schemeSteps = c.flavors.map((f) => '''
   - **$f**
     - Duplicate the `Runner` scheme and rename it to `$f`.
     - Edit the scheme → for each action (Run, Profile, Archive), set the
       **Build Configuration** to the matching `*-$f` configuration created
       in step 2.''').join('\n');
    final configSteps = c.flavors.map((f) => '''
   - From each base configuration (`Debug`, `Release`, `Profile`), duplicate
     and rename to `Debug-$f`, `Release-$f`, `Profile-$f`.''').join('\n');

    return '''
# iOS Flavor Setup

Flutter automates Android flavors, but iOS flavors require a one-time manual
setup in Xcode. This project defines these flavors: $flavorList.

Follow Flutter's official guide alongside these steps:
https://docs.flutter.dev/deployment/flavors-ios

## 1. Open the iOS project in Xcode

```bash
open ios/Runner.xcworkspace
```

## 2. Create build configurations

In Xcode, select the **Runner** project → **Info** tab → **Configurations**.
$configSteps

## 3. Create a scheme per flavor

In Xcode, **Product → Scheme → Manage Schemes…**.
$schemeSteps

   Tick **Shared** for each new scheme so it is committed to version control.

## 4. Set the bundle identifier suffix per flavor (optional)

To install multiple flavors side by side, give each a distinct bundle ID:

1. Select the **Runner** target → **Build Settings**.
2. Search for **Product Bundle Identifier**.
3. Expand it and set a per-configuration value, e.g.
   `com.example.app.dev` for the `*-dev` configurations.

   (This mirrors the Android `applicationIdSuffix` already configured in
   `android/app/build.gradle.kts`.)

## 5. Set the display name per flavor (optional)

To show a flavor-specific app name on the home screen:

1. Select the **Runner** target → **Build Settings** → add a User-Defined
   setting, e.g. `APP_DISPLAY_NAME`, with a per-configuration value.
2. In `ios/Runner/Info.plist`, set
   `<key>CFBundleDisplayName</key><string>\$(APP_DISPLAY_NAME)</string>`.

## 6. Run

```bash
$runExample
```

Xcode picks the scheme matching the `--flavor` value. Verify each flavor
launches and installs as expected before shipping.
''';
  }

  static String gitignore(ProjectConfig c) => '''
# Miscellaneous
*.class
*.log
*.swp
.DS_Store
.atom/
.svn/
migrate_working_dir/

# IntelliJ / Android Studio
*.iml
*.ipr
*.iws
.idea/

# VS Code
${c.hasFlavors ? '.vscode/*\n!.vscode/launch.json' : '.vscode/'}

# Flutter / Dart / Pub
**/doc/api/
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.pub-cache/
.pub/
/build/

# Android
android/.gradle
android/captures/
android/local.properties
android/key.properties
*.jks

# iOS
**/ios/Flutter/.last_build_id
**/ios/Flutter/Generated.xcconfig
**/ios/Flutter/ephemeral
**/ios/Pods/
**/ios/.symbols/
**/ios/**/xcuserdata
''';
}
