import 'package:srik_cli/models/project_config.dart';
import 'package:srik_cli/utils/string_utils.dart';

/// Templates shared across all architectures.
class CommonTemplates {
  static String pubspec(ProjectConfig c) => '''
name: ${c.projectName}
description: ${c.description}
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.0.0

  # Networking
  dio: ^5.4.0

  # Local storage
  shared_preferences: ^2.2.0

  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
''';

  static String analysisOptions(ProjectConfig c) => '''
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    require_trailing_commas: true

analyzer:
  errors:
    invalid_annotation_target: ignore
''';

  static String srikYaml(ProjectConfig c) => '''
# srik_cli configuration.
#
# This file is read by `srik add feature` and `srik add screen` to know
# how to generate new code. It is rewritten when features are appended.
# Avoid adding comments below — they will not be preserved on regeneration.
#
# Fields:
#   project_name      Dart package name (lowercase + underscores).
#   architecture      clean | mvvm | feature-first | simple.
#   state_management  Always "riverpod" in v0.3 (more options planned).
#   routing           Always "go_router" in v0.3.
#   storage           Always "shared_preferences" in v0.3.
#   network           Always "dio" in v0.3.
#   design_system.preset      material | vibrant | minimal.
#   design_system.gradient    true to include app_gradients.dart.
#   design_system.spacing     compact | normal | spacious.
#   design_system.brand_color #RRGGBB or #AARRGGBB.
#   features                  Tracked feature names, one per line.
version: 0.2.0
project_name: ${c.projectName}
architecture: ${c.architecture.id}
state_management: riverpod
routing: go_router
storage: shared_preferences
network: dio
design_system:
  preset: ${c.designPreset.id}
  gradient: ${c.useGradient}
  spacing: ${c.spacingScale.id}
  brand_color: "${c.brandColor}"
features:
  - home
''';

  static String readme(ProjectConfig c) {
    final title = StringUtils.toTitleCase(c.projectName);
    return '''
# $title

${c.description}

Generated by [srik_cli](https://pub.dev/packages/srik_cli).

## Configuration

- **Architecture:** ${c.architecture.label}
- **State management:** Riverpod
- **Routing:** go_router
- **Networking:** Dio
- **Local storage:** shared_preferences
- **Design preset:** ${c.designPreset.id}
- **Gradient theme:** ${c.useGradient ? 'enabled' : 'disabled'}
- **Spacing scale:** ${c.spacingScale.id}

## Run

```bash
flutter pub get
flutter run
```

## Add features

```bash
srik add feature <feature_name>
```

## License

Add your license here.
''';
  }

  static String gitignore(ProjectConfig c) => '''
# Miscellaneous
*.class
*.log
*.swp
.DS_Store
.atom/
.svn/
migrate_working_dir/

# IntelliJ / Android Studio
*.iml
*.ipr
*.iws
.idea/

# VS Code
.vscode/

# Flutter / Dart / Pub
**/doc/api/
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.pub-cache/
.pub/
/build/

# Android
android/.gradle
android/captures/
android/local.properties
android/key.properties
*.jks

# iOS
**/ios/Flutter/.last_build_id
**/ios/Flutter/Generated.xcconfig
**/ios/Flutter/ephemeral
**/ios/Pods/
**/ios/.symbols/
**/ios/**/xcuserdata
''';
}
