import 'package:srik_cli/models/project_config.dart';
import 'package:srik_cli/utils/string_utils.dart';

/// Simple template set — minimal structure, no architecture layering.
/// Design files live in lib/theme/.
class SimpleTemplates {
  static const String designDir = 'theme';

  static Map<String, String> files(ProjectConfig c) {
    final name = c.projectName;
    final title = StringUtils.toTitleCase(name);

    return {
      'lib/main.dart': '''
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';

void main() {
  runApp(
    const ProviderScope(
      child: MyApp(),
    ),
  );
}
''',
      'lib/app.dart': '''
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:$name/theme/app_theme.dart';
import 'package:$name/router/app_router.dart';

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    return MaterialApp.router(
      title: '$title',
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      routerConfig: router,
      debugShowCheckedModeBanner: false,
    );
  }
}
''',
      'lib/router/app_router.dart': '''
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:$name/screens/home_screen.dart';

final appRouterProvider = Provider<GoRouter>((ref) {
  return GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        name: 'home',
        builder: (context, state) => const HomeScreen(),
      ),
    ],
  );
});
''',
      'lib/services/api_service.dart': '''
import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final dioProvider = Provider<Dio>((ref) {
  final dio = Dio(
    BaseOptions(
      baseUrl: 'https://api.example.com',
      connectTimeout: const Duration(seconds: 10),
      receiveTimeout: const Duration(seconds: 10),
    ),
  );
  dio.interceptors.add(LogInterceptor(responseBody: true));
  return dio;
});
''',
      'lib/models/welcome_model.dart': '''
import 'package:equatable/equatable.dart';

class WelcomeModel extends Equatable {
  final String title;
  final String subtitle;

  const WelcomeModel({required this.title, required this.subtitle});

  @override
  List<Object?> get props => [title, subtitle];
}
''',
      'lib/screens/home_screen.dart': '''
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:$name/models/welcome_model.dart';
import 'package:$name/theme/app_colors.dart';
import 'package:$name/theme/app_spacing.dart';
import 'package:$name/theme/app_text_styles.dart';

final welcomeProvider = FutureProvider<WelcomeModel>((ref) async {
  await Future.delayed(const Duration(milliseconds: 300));
  return const WelcomeModel(
    title: 'Welcome',
    subtitle: 'Your app is ready. Start building!',
  );
});

class HomeScreen extends ConsumerWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(welcomeProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('$title')),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(AppSpacing.lg),
          child: state.when(
            loading: () =>
                const Center(child: CircularProgressIndicator()),
            error: (e, _) => Center(
              child: Text(
                'Error: \$e',
                style: AppTextStyles.body.copyWith(color: AppColors.error),
              ),
            ),
            data: (model) => Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(model.title, style: AppTextStyles.h1),
                const SizedBox(height: AppSpacing.sm),
                Text(model.subtitle, style: AppTextStyles.body),
                const Spacer(),
                Center(
                  child: ElevatedButton(
                    onPressed: () => ref.invalidate(welcomeProvider),
                    child: const Text('Refresh'),
                  ),
                ),
                const SizedBox(height: AppSpacing.lg),
                const Center(
                  child: Text(
                    'Generated by srik_cli',
                    style: AppTextStyles.caption,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
''',
      'lib/widgets/.gitkeep': '',
    };
  }
}
